import { FinancialInsights } from "./types";

export const SAMPLE_INSIGHTS: FinancialInsights = {
  statementPeriod: "September 1 - September 28, 2026",
  accountHolder: "Alex Morgan",
  totalSpent: 3418.50,
  totalIncome: 5200.00,
  netSavings: 1781.50,
  savingsRate: 34.2,
  averageDailySpend: 122.09,
  healthScore: 82,
  financialPersona: "The Weekend Gourmet & Tech Nibbler 🍣💻",
  personaDescription: "You budget like a disciplined Swiss banker Monday through Thursday, but the moment Friday evening rolls in, Uber Eats and gadget pre-orders take the wheel!",
  summary: "Overall stellar financial health! You saved 34.2% of your take-home income this month ($1,781.50). Housing and essential utilities are steady at 38% of your outflows. Your biggest discretionary leak remains food delivery and weekend entertainment, where 22% of total spend occurred.",
  funnyObservation: "You bought 14 separate iced matchas this month ($94 total) while having an unopened $60 ceremonial matcha tin in your kitchen cabinet. We respect the dedication to the barista economy.",
  actionableTips: [
    "You have 4 active streaming/cloud subscriptions totaling $74/month — 2 haven't shown active billing usage.",
    "Swapping 3 weekend delivery orders for home-cooked meals would boost your monthly savings by ~$220.",
    "Your highest single spending day was Saturday Sept 12th ($412) — mostly shopping and dinner with friends."
  ],
  topCategories: [
    { category: "Housing & Rent", total: 1450.00, percentage: 42.4, count: 1, emoji: "🏠", color: "#818CF8" },
    { category: "Food & Dining", total: 685.20, percentage: 20.0, count: 28, emoji: "🍔", color: "#F43F5E" },
    { category: "Shopping & Gadgets", total: 412.30, percentage: 12.1, count: 6, emoji: "🛍️", color: "#F59E0B" },
    { category: "Transportation", total: 295.00, percentage: 8.6, count: 14, emoji: "🚗", color: "#06B6D4" },
    { category: "Subscriptions & Tech", total: 184.00, percentage: 5.4, count: 7, emoji: "⚡", color: "#10B981" },
    { category: "Entertainment & Fun", total: 242.00, percentage: 7.1, count: 5, emoji: "🎟️", color: "#EC4899" },
    { category: "Health & Fitness", total: 150.00, percentage: 4.4, count: 3, emoji: "💪", color: "#8B5CF6" },
  ],
  largestExpenses: [
    { date: "Sep 01", description: "CityLofts Property Rent", amount: 1450.00, category: "Housing & Rent", type: "expense" },
    { date: "Sep 12", description: "Apple Store - Mechanical Keyboard & Hub", amount: 249.00, category: "Shopping & Gadgets", type: "expense" },
    { date: "Sep 19", description: "Costco Wholesale Bulk Run", amount: 184.20, category: "Food & Dining", type: "expense" },
    { date: "Sep 05", description: "Equinox Gym Monthly Membership", amount: 150.00, category: "Health & Fitness", type: "expense" },
    { date: "Sep 22", description: "Omakase Sushi Night w/ Friends", amount: 135.50, category: "Food & Dining", type: "expense" }
  ],
  subscriptions: [
    { name: "Equinox Fitness", amount: 150.00, frequency: "Monthly", category: "Health" },
    { name: "ChatGPT Plus", amount: 20.00, frequency: "Monthly", category: "Tech & AI" },
    { name: "Spotify Premium Duo", amount: 16.99, frequency: "Monthly", category: "Entertainment" },
    { name: "iCloud+ 2TB Storage", amount: 9.99, frequency: "Monthly", category: "Cloud" },
    { name: "Netflix Standard HD", amount: 15.49, frequency: "Monthly", category: "Entertainment" }
  ],
  dailySpending: [
    { date: "Sep 01", total: 1472.00, dayOfWeek: "Tue" },
    { date: "Sep 02", total: 18.50, dayOfWeek: "Wed" },
    { date: "Sep 03", total: 42.00, dayOfWeek: "Thu" },
    { date: "Sep 04", total: 85.30, dayOfWeek: "Fri" },
    { date: "Sep 05", total: 215.00, dayOfWeek: "Sat" },
    { date: "Sep 06", total: 34.20, dayOfWeek: "Sun" },
    { date: "Sep 07", total: 12.00, dayOfWeek: "Mon" },
    { date: "Sep 08", total: 26.50, dayOfWeek: "Tue" },
    { date: "Sep 09", total: 48.00, dayOfWeek: "Wed" },
    { date: "Sep 10", total: 19.90, dayOfWeek: "Thu" },
    { date: "Sep 11", total: 95.00, dayOfWeek: "Fri" },
    { date: "Sep 12", total: 412.30, dayOfWeek: "Sat" },
    { date: "Sep 13", total: 54.00, dayOfWeek: "Sun" },
    { date: "Sep 14", total: 15.00, dayOfWeek: "Mon" },
    { date: "Sep 15", total: 68.40, dayOfWeek: "Tue" },
    { date: "Sep 16", total: 22.00, dayOfWeek: "Wed" },
    { date: "Sep 17", total: 45.00, dayOfWeek: "Thu" },
    { date: "Sep 18", total: 112.50, dayOfWeek: "Fri" },
    { date: "Sep 19", total: 245.20, dayOfWeek: "Sat" },
    { date: "Sep 20", total: 38.00, dayOfWeek: "Sun" },
    { date: "Sep 21", total: 18.00, dayOfWeek: "Mon" },
    { date: "Sep 22", total: 165.50, dayOfWeek: "Tue" },
    { date: "Sep 23", total: 29.00, dayOfWeek: "Wed" },
    { date: "Sep 24", total: 35.00, dayOfWeek: "Thu" },
    { date: "Sep 25", total: 89.00, dayOfWeek: "Fri" },
    { date: "Sep 26", total: 140.00, dayOfWeek: "Sat" },
    { date: "Sep 27", total: 32.00, dayOfWeek: "Sun" },
    { date: "Sep 28", total: 24.20, dayOfWeek: "Mon" }
  ],
  allTransactions: [
    { date: "Sep 01", description: "CityLofts Property Rent", amount: 1450.00, category: "Housing & Rent", type: "expense" },
    { date: "Sep 01", description: "Direct Deposit - TechCorp Payroll", amount: 2600.00, category: "Income", type: "income" },
    { date: "Sep 01", description: "Morning Blue Bottle Coffee", amount: 7.50, category: "Food & Dining", type: "expense" },
    { date: "Sep 02", description: "Whole Foods Deli Lunch", amount: 18.50, category: "Food & Dining", type: "expense" },
    { date: "Sep 03", description: "Metro Pass Refill", amount: 42.00, category: "Transportation", type: "expense" },
    { date: "Sep 04", description: "Trader Joe's Groceries", amount: 85.30, category: "Food & Dining", type: "expense" },
    { date: "Sep 05", description: "Equinox Gym Monthly Membership", amount: 150.00, category: "Health & Fitness", type: "expense" },
    { date: "Sep 05", description: "Dinner at Little Italy", amount: 65.00, category: "Food & Dining", type: "expense" },
    { date: "Sep 08", description: "Uber Ride Home", amount: 26.50, category: "Transportation", type: "expense" },
    { date: "Sep 11", description: "Cocktails with Coworkers", amount: 95.00, category: "Entertainment & Fun", type: "expense" },
    { date: "Sep 12", description: "Apple Store - Mechanical Keyboard & Hub", amount: 249.00, category: "Shopping & Gadgets", type: "expense" },
    { date: "Sep 12", description: "Weekend Brunch & Mimosas", amount: 63.30, category: "Food & Dining", type: "expense" },
    { date: "Sep 15", description: "Direct Deposit - TechCorp Payroll", amount: 2600.00, category: "Income", type: "income" },
    { date: "Sep 15", description: "Electric & Gas Utility Bill", amount: 68.40, category: "Housing & Rent", type: "expense" },
    { date: "Sep 18", description: "Cinema Tickets & Popcorn", amount: 44.50, category: "Entertainment & Fun", type: "expense" },
    { date: "Sep 19", description: "Costco Wholesale Bulk Run", amount: 184.20, category: "Food & Dining", type: "expense" },
    { date: "Sep 22", description: "Omakase Sushi Night w/ Friends", amount: 135.50, category: "Food & Dining", type: "expense" },
    { date: "Sep 25", description: "Concert Ticket (Indie Fest)", amount: 89.00, category: "Entertainment & Fun", type: "expense" },
    { date: "Sep 26", description: "Zara Autumn Jacket", amount: 110.00, category: "Shopping & Gadgets", type: "expense" }
  ]
};
